### ISSUE TITLE
Ability to use CSS variable for color

### ISSUE THREAD

**Issue by nabilfatih** [Skyleen77/next-nprogress-bar#41]
If I can use my CSS variable in color props, that would be good, since I have a lot of theme in the application

**Comment by Skyleen77** [comment]
Hello, you can do something like that for exemple : 
CSS:
```css
:root {
  --nprogress-color: red;
  --nprogress-height: 20px;
}
```
JS: 
```javascript
<ProgressBar
   height="var(--nprogress-height)"
   color="var(--nprogress-color)"
/>
```
