### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by 3li7u** [Skyleen77/next-nprogress-bar#61]
Hello there!
how can I make the progress bar support rtl direction?
I tried this but it doesn't work
```css
#nprogress .bar {
          position: fixed;
          top: 0;
          inset-inline-start: 0; /* instate of left: 0; */
          z-index: 1031;
          width: 100%;
          height: 4px;
        }
```
and this also
```css
#nprogress .bar {
         left: ${isRTL ? "unset" : "0"},
          right: ${isRTL ? "0" : "unset"},
        }
```
